export const Categoris = [
    {
      id: "cat-1",
      name: "Power Equipment",
      desc: `Best Power is your go-to source for reliable power equipment. We import and distribute a wide
      range of essential power solutions, including transformers, generators, powerbacks, inverters,
      batteries, rectifiers, car chargers, and Automatic Voltage Regulators (AVRs). Our commitment to
      quality and choice ensures that you have access to the most dependable and efficient power
      infrastructure.`,
      products: [
        {
          cat_id: "cat-1",
          id: "prod-1",
          slug: "transformers",
          name: "Transformers",
          images: [
            "https://5.imimg.com/data5/DO/TR/MY-20560234/mva-power-transformer-500x500.jpg",
            "https://onlinesciencenotes.com/wp-content/uploads/2020/09/transformer.jpg",
            "https://www.ge.com/news/sites/default/files/Reports/2021-10/Screen%20Shot%202021-10-27%20at%208.00.59%20AM.jpg",
            "https://vietnamtransformer.com/upload/news/1605061534_Untitled-2.jpg",
          ],
          desc: `We import transformers, essential devices that
          regulate voltage levels, ensuring the safe and efficient
          distribution of electrical energy.`,
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "generators",
          name: "Generators",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: `Best Power sources high-quality generators to provide
          reliable backup power, ensuring continuity during
          electrical outages or in areas without grid access.`,
        },
        {
          cat_id: "cat-1",
          id: "prod-3",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-4",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-5",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-6",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-7",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-8",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-9",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-10",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-11",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-12",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-13",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
        {
          cat_id: "cat-1",
          id: "prod-14",
          slug: "full-electric-car-equipment",
          name: "AVR",
          images: [
            "https://powerwalker.com/wp-content/uploads/2022/02/PowerWalker-AVR-2000-SIV_right.jpg",
            "https://ae01.alicdn.com/kf/U2ea8de73b3274466aaa3a39ea8896ceaU/Voltage-stabilizer-avr-1000-600-W-1000-a-ippon-551688.jpg",
            "https://m.media-amazon.com/images/I/51WnAj0iaZL._AC_UF894,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61TnP9sxtpL._AC_UF894,1000_QL80_.jpg",
          ],
          desc: "Welcome to BEST POWER - your one-stop destination for premium power equipment, electrical accessories, and turnkey EPC projects. Discover innovative energy solutions with our relentless commitment to excellence.",
        },
      ],
    },
  
    {
      id: "cat-2",
      name: "ICT Equipment",
      desc: "This is ICT Equipments are available with us for your needs and requirements. We are the leading ICT Equipment supplier in Sri Lanka.",
      products: [
        {
          cat_id: "cat-2",
          id: "prod-1",
          slug: "Fiber-Optic-Cable",
          name: "Fiber Optic Cable",
          images: [
            "https://4.imimg.com/data4/NB/EE/MY-4493487/4-core-fiber-optic-cable.jpg",
            "https://m.media-amazon.com/images/I/61NywiGpkeL._AC_UF1000,1000_QL80_.jpg",
            "https://m.media-amazon.com/images/I/61AUckRyDZL._AC_UF1000,1000_QL80_.jpg",
            "https://www.multicominc.com/wp-content/uploads/Draka_ezSPAN.png",
          ],
          desc: "Find the best Fiber Optic Cable price in Sri Lanka. We are the leading Fiber Optic Cable supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
        {
          cat_id: "cat-1",
          id: "prod-2",
          slug: "Servers",
          name: "Servers",
          images: [
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/rack-server.jpg",
            "https://au.insight.com/content/dam/insight-web/sitesections/buy/products/tower-server.jpg",
            "https://microless.com/cdn/products/03151c99fcdece4633fd852a55e220e3-md.jpg",
            "https://www.energypower.gr/wp-content/uploads/2019/10/AVR-1.jpg",
          ],
          desc: "Find the best Servers price in Sri Lanka. We are the leading Servers supplier in Sri Lanka.",
        },
      ],
    },
  ];
  